### ISSUE TITLE
checkpoint can not be loaded

### ISSUE THREAD

**Issue by haoyuying** [jantic/DeOldify#259]
I  have downloaded the checkpoint from https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0, however, it can not be used.
File "app-video.py", line 81, in <module>
    video_colorizer = get_video_colorizer()
  File "/ssd3/haoyuying/DeOldify/deoldify/visualize.py", line 357, in get_video_colorizer
    return get_stable_video_colorizer(render_factor=render_factor)
  File "/ssd3/haoyuying/DeOldify/deoldify/visualize.py", line 379, in get_stable_video_colorizer
    learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
  File "/ssd3/haoyuying/DeOldify/deoldify/generators.py", line 15, in gen_inference_wide
    learn.load(weights_name)
  File "/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/fastai/basic_train.py", line 269, in load
    get_model(self.model).load_state_dict(model_state, strict=strict)
  File "/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DynamicUnetWide:
	size mismatch for layers.3.0.0.weight: copying a param of torch.Size([4096, 2048, 3, 3]) from checkpoint, where the shape is torch.Size([18432]) in current model.
	size mismatch for layers.3.1.0.weight: copying a param of torch.Size([2048, 4096, 3, 3]) from checkpoint, where the shape is torch.Size([36864]) in current model.
	size mismatch for layers.4.shuf.conv.0.weight: copying a param of torch.Size([2048, 2048, 1, 1]) from checkpoint, where the shape is torch.Size([2048]) in current model.
	size mismatch for layers.4.conv.0.weight: copying a param of torch.Size([512, 1536, 3, 3]) from checkpoint, where the shape is torch.Size([13824]) in current model.
	size mismatch for layers.5.shuf.conv.0.weight: copying a param of torch.Size([2048, 512, 1, 1]) from checkpoint, where the shape is torch.Size([512]) in current model.
	size mismatch for layers.5.conv.0.weight: copying a param of torch.Size([512, 1024, 3, 3]) from checkpoint, where the shape is torch.Size([9216]) in current model.
	size mismatch for layers.5.conv.3.query.weight: copying a param of torch.Size([64, 512, 1]) from checkpoint, where the shape is torch.Size([512]) in current model.
	size mismatch for layers.5.conv.3.key.weight: copying a param of torch.Size([64, 512, 1]) from checkpoint, where the shape is torch.Size([512]) in current model.
	size mismatch for layers.5.conv.3.value.weight: copying a param of torch.Size([512, 512, 1]) from checkpoint, where the shape is torch.Size([512]) in current model.
	size mismatch for layers.6.shuf.conv.0.weight: copying a param of torch.Size([2048, 512, 1, 1]) from checkpoint, where the shape is torch.Size([512]) in current model.
	size mismatch for layers.6.conv.0.weight: copying a param of torch.Size([512, 768, 3, 3]) from checkpoint, where the shape is torch.Size([6912]) in current model.
	size mismatch for layers.7.shuf.conv.0.weight: copying a param of torch.Size([1024, 512, 1, 1]) from checkpoint, where the shape is torch.Size([512]) in current model.
	size mismatch for layers.7.conv.0.weight: copying a param of torch.Size([256, 320, 3, 3]) from checkpoint, where the shape is torch.Size([2880]) in current model.
	size mismatch for layers.10.layers.0.0.weight: copying a param of torch.Size([259, 259, 3, 3]) from checkpoint, where the shape is torch.Size([2331]) in current model.
	size mismatch for layers.10.layers.1.0.weight: copying a param of torch.Size([259, 259, 3, 3]) from checkpoint, where the shape is torch.Size([2331]) in current model.
	size mismatch for layers.11.0.weight: copying a param of torch.Size([3, 259, 1, 1]) from checkpoint, where the shape is torch.Size([259]) in current model.

**Comment by jantic** [comment]
@haoyuying I'm not able to reproduce your issue.  I think it might be possible that the model download is corrupted and should be tried again. I'm not sure what else it could be if not that..

**Comment by haoyuying** [comment]
For the first time I use "python app-vedio.py", it download the checkpoint from 'https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0',and has these error:

 File "app-video.py", line 83, in <module>
    video_colorizer = get_video_colorizer()
  File "/ssd3/haoyuying/DeOldify1/deoldify/visualize.py", line 357, in get_video_colorizer
    return get_stable_video_colorizer(render_factor=render_factor)
  File "/ssd3/haoyuying/DeOldify1/deoldify/visualize.py", line 378, in get_stable_video_colorizer
    learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
  File "/ssd3/haoyuying/DeOldify1/deoldify/generators.py", line 18, in gen_inference_wide
    learn.load_state_dict(torch.load('/ssd3/haoyuying/DeOldify/data/models/ColorizeVideo_gen'))
AttributeError: 'Learner' object has no attribute 'load_state_dict'
(GPU-Paddle-3) [haoyuying@yq01-qianmo-com-255-129-12.yq01.baidu.com DeOldify1]$ python app-video.py 
/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/fastai/data_block.py:442: UserWarning: Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.
  warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/fastai/data_block.py:445: UserWarning: Your validation set is empty. If this is by design, use `split_none()`
                 or pass `ignore_empty=True` when labelling to remove this warning.
  or pass `ignore_empty=True` when labelling to remove this warning.""")
Traceback (most recent call last):
  File "app-video.py", line 83, in <module>
    video_colorizer = get_video_colorizer()
  File "/ssd3/haoyuying/DeOldify1/deoldify/visualize.py", line 357, in get_video_colorizer
    return get_stable_video_colorizer(render_factor=render_factor)
  File "/ssd3/haoyuying/DeOldify1/deoldify/visualize.py", line 378, in get_stable_video_colorizer
    learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
  File "/ssd3/haoyuying/DeOldify1/deoldify/generators.py", line 19, in gen_inference_wide
    learn.load(weights_name)
  File "/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/fastai/basic_train.py", line 269, in load
    get_model(self.model).load_state_dict(model_state, strict=strict)
  File "/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DynamicUnetWide:
	Missing key(s) in state_dict: "layers.3.0.0.weight", "layers.3.1.0.weight", "layers.4.shuf.conv.0.weight", "layers.4.conv.0.weight", "layers.5.shuf.conv.0.weight", "layers.5.conv.0.weight", "layers.5.conv.3.query.weight", "layers.5.conv.3.key.weight", "layers.5.conv.3.value.weight", "layers.6.shuf.conv.0.weight", "layers.6.conv.0.weight", "layers.7.shuf.conv.0.weight", "layers.7.conv.0.weight", "layers.10.layers.0.0.weight", "layers.10.layers.1.0.weight", "layers.11.0.weight". 
	Unexpected key(s) in state_dict: "layers.3.0.0.weight_v", "layers.3.1.0.weight_v", "layers.4.shuf.conv.0.weight_v", "layers.4.conv.0.weight_v", "layers.5.shuf.conv.0.weight_v", "layers.5.conv.0.weight_v", "layers.5.conv.3.query.weight_v", "layers.5.conv.3.key.weight_v", "layers.5.conv.3.value.weight_v", "layers.6.shuf.conv.0.weight_v", "layers.6.conv.0.weight_v", "layers.7.shuf.conv.0.weight_v", "layers.7.conv.0.weight_v", "layers.10.layers.0.0.weight_v", "layers.10.layers.1.0.weight_v", "layers.11.0.weight_v". 

so ,I change the key name in the checkpoint, and it has the above problem(details in first issue). I show the model and the checkpoint, they do not match. For example,
layers.3.0.0.weight_orig torch.Size([4096, 2048, 3, 3])
layers.3.0.0.weight torch.Size([4096, 2048, 3, 3])
layers.3.0.0.weight_u torch.Size([4096])  for model, 

 layers.3.0.0.weight_orig torch.Size([4096, 2048, 3, 3])
layers.3.0.0.weight_u torch.Size([4096])
layers.3.0.0.weight_v torch.Size([18432]) for checkpoint.

**Comment by haoyuying** [comment]
For the first time I use "python app-vedio.py", it download the checkpoint from 'https://www.dropbox.com/s/336vn9y4qwyg9yz/ColorizeVideo_gen.pth?dl=0',and has these error:


$ python app-video.py
/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/fastai/data_block.py:442: UserWarning: Your training set is empty. If this is by design, pass ignore_empty=True to remove this warning.
warn("Your training set is empty. If this is by design, pass ignore_empty=True to remove this warning.")
/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/fastai/data_block.py:445: UserWarning: Your validation set is empty. If this is by design, use split_none()
or pass ignore_empty=True when labelling to remove this warning.
or pass ignore_empty=True when labelling to remove this warning.""")
Traceback (most recent call last):
File "app-video.py", line 83, in 
video_colorizer = get_video_colorizer()
File "/ssd3/haoyuying/DeOldify1/deoldify/visualize.py", line 357, in get_video_colorizer
return get_stable_video_colorizer(render_factor=render_factor)
File "/ssd3/haoyuying/DeOldify1/deoldify/visualize.py", line 378, in get_stable_video_colorizer
learn = gen_inference_wide(root_folder=root_folder, weights_name=weights_name)
File "/ssd3/haoyuying/DeOldify1/deoldify/generators.py", line 19, in gen_inference_wide
learn.load(weights_name)
File "/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/fastai/basic_train.py", line 269, in load
get_model(self.model).load_state_dict(model_state, strict=strict)
File "/ssd3/haoyuying/anaconda2/envs/GPU-Paddle-3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
self.class.name, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for DynamicUnetWide:
Missing key(s) in state_dict: "layers.3.0.0.weight", "layers.3.1.0.weight", "layers.4.shuf.conv.0.weight", "layers.4.conv.0.weight", "layers.5.shuf.conv.0.weight", "layers.5.conv.0.weight", "layers.5.conv.3.query.weight", "layers.5.conv.3.key.weight", "layers.5.conv.3.value.weight", "layers.6.shuf.conv.0.weight", "layers.6.conv.0.weight", "layers.7.shuf.conv.0.weight", "layers.7.conv.0.weight", "layers.10.layers.0.0.weight", "layers.10.layers.1.0.weight", "layers.11.0.weight".
Unexpected key(s) in state_dict: "layers.3.0.0.weight_v", "layers.3.1.0.weight_v", "layers.4.shuf.conv.0.weight_v", "layers.4.conv.0.weight_v", "layers.5.shuf.conv.0.weight_v", "layers.5.conv.0.weight_v", "layers.5.conv.3.query.weight_v", "layers.5.conv.3.key.weight_v", "layers.5.conv.3.value.weight_v", "layers.6.shuf.conv.0.weight_v", "layers.6.conv.0.weight_v", "layers.7.shuf.conv.0.weight_v", "layers.7.conv.0.weight_v", "layers.10.layers.0.0.weight_v", "layers.10.layers.1.0.weight_v", "layers.11.0.weight_v".

so ,I change the key name in the checkpoint, and it has the above problem(details in first issue). I show the model and the checkpoint, they do not match. For example,
layers.3.0.0.weight_orig torch.Size([4096, 2048, 3, 3])
layers.3.0.0.weight torch.Size([4096, 2048, 3, 3])
layers.3.0.0.weight_u torch.Size([4096]) for model,

layers.3.0.0.weight_orig torch.Size([4096, 2048, 3, 3])
layers.3.0.0.weight_u torch.Size([4096])
layers.3.0.0.weight_v torch.Size([18432]) for checkpoint.

**Comment by jantic** [comment]
@haoyuying I simply can't reproduce your issue.  I'd try deleting the video model at /ssd3/haoyuying/DeOldify1/data/models/ and trying again.

**Comment by jantic** [comment]
Closing due to inactivity.
