### ISSUE TITLE
Docker for API

### ISSUE THREAD

**Issue by McFalljb** [jantic/DeOldify#260]
Hello ive been interested in using DAIN locally so decided to give the Docker API a shot. 

Whenever I run (im using 0.0.0.0:5000 because MY_SUPER_API_IP:5000 is not recognized)

```
curl -X POST "0.0.0.0:5000/process" -H "accept: application/octet-stream" -H "Content-Type: application/json" -d "{\"source_url\":\"https://www.dropbox.com/s/8r3nzs3bvw43vks/hindenberg_explodes_edit.mp4\", \"render_factor\":35}" --output colorized_video.mp4
```

I receive a 500 error and the docker logs show what is posted below.

```
Traceback (most recent call last):
  File "app.py", line 53, in process_image
    render_factor=render_factor, display_render_factor=True, compare=False)
  File "/data/deoldify/visualize.py", line 105, in plot_transformed_image
    path, render_factor, post_process=post_process,watermarked=watermarked
  File "/data/deoldify/visualize.py", line 170, in get_transformed_image
    orig_image = self._open_pil_image(path)
  File "/data/deoldify/visualize.py", line 62, in _open_pil_image
    return PIL.Image.open(path).convert('RGB')
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file '/data/upload/ff0c5e5b-b073-45e1-8045-9814ff445af7.jpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 55, in process_image
    convertToJPG(input_path)
  File "/data/app_utils.py", line 38, in convertToJPG
    img = Image.open(path_original)
  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file '/data/upload/ff0c5e5b-b073-45e1-8045-9814ff445af7.jpeg'
[2020-07-31 02:36:16,836] ERROR in app: Exception on /process [POST]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/opt/conda/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/opt/conda/lib/python3.6/site-packages/werkzeug/test.py", line 1118, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1982, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/opt/conda/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/flask/app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/opt/conda/lib/python3.6/site-packages/werkzeug/wrappers/base_response.py", line 269, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/opt/conda/lib/python3.6/site-packages/werkzeug/test.py", line 1118, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.
172.17.0.1 - - [31/Jul/2020 02:36:16] "POST /process HTTP/1.1" 500 -

```

Hoping someone can shed some light on this. Is there an easier way to run this locally?

**Comment by jantic** [comment]
So there's a few things going on here.  First, you're running image processing docker so it's expecting an image, not a video.  Hence it's complaining about not being able to identify the "image file". You'd want to run app-video.py for video and to do that you'll have to change CMD in https://github.com/jantic/DeOldify/blob/master/Dockerfile-api accordingly. I don't use the docker functionality personally so I can't 100% say if that's sufficient without digging further.

But really more than anything what I'd recommend if you simply want to run this stuff locally is just use the Jupyter notebooks and run jupyter lab, rather than trying to use docker.  My argument is that it's a lot more interactive and gives you more useful feedback, and is easier to identify issues. It gives you a nice UI to work with.

**Comment by McFalljb** [comment]
Well its funny you are saying that im using the image processing im following your directions for video. Based off the directions in this repo you cant run it locally.

**Comment by jantic** [comment]
Yeah you're absolutely right that there's no indication in the directions that this will come up as an issue.  So the api is a bit confusing as a result and so are the directions. Really what we need I think is a change in the api so that it's clean and you don't have edit the files for this.  

@jqueguiner  Since you'd be affected by this, what do you think of making the video and image Docker-api deployments 100% cleanly separated so that no editing of the Dockerfile-api file is required to deploy them?  Perhaps just making a separate Dockerfile-video-api and Dockerfile-image-api would suffice?
