### ISSUE TITLE
Docker image_api fails to run with "No space left on device"

### ISSUE THREAD

**Issue by sklv** [jantic/DeOldify#298]
Hi,

I am trying to run a local image_api instance with `./quick_start.sh image_api`.

The docker image is built successfully, however when ran quits immediately with the output below.

I am using vanilla docker with an RX 570 GPU. Is this a supported configuration?

I have a suspicion that an Nvidia GPU is required, but this isn't explicitly mentioned anywhere.

```
=============
== PyTorch ==
=============

NVIDIA Release 19.04 (build 6089340)
PyTorch Version 1.1.0a0+9eb0f43

Container image Copyright (c) 2019, NVIDIA CORPORATION.  All rights reserved.

Copyright (c) 2014-2019 Facebook Inc.
Copyright (c) 2011-2014 Idiap Research Institute (Ronan Collobert)
Copyright (c) 2012-2014 Deepmind Technologies    (Koray Kavukcuoglu)
Copyright (c) 2011-2012 NEC Laboratories America (Koray Kavukcuoglu)
Copyright (c) 2011-2013 NYU                      (Clement Farabet)
Copyright (c) 2006-2010 NEC Laboratories America (Ronan Collobert, Leon Bottou, Iain Melvin, Jason Weston)
Copyright (c) 2006      Idiap Research Institute (Samy Bengio)
Copyright (c) 2001-2004 Idiap Research Institute (Ronan Collobert, Samy Bengio, Johnny Mariethoz)
Copyright (c) 2015      Google Inc.
Copyright (c) 2015      Yangqing Jia
Copyright (c) 2013-2016 The Caffe contributors
All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.
NVIDIA modifications are covered by the license terms that apply to the underlying project or file.

WARNING: The NVIDIA Driver was not detected.  GPU functionality will not be available.
   Use 'nvidia-docker run' to start this container; see
   https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker .

NOTE: MOFED driver for multi-node communication was not detected.
      Multi-node communication performance may be reduced.

NOTE: The SHMEM allocation limit is set to the default of 64MB.  This may be
   insufficient for PyTorch.  NVIDIA recommends the use of the following flags:
   nvidia-docker run --ipc=host ...

/opt/conda/lib/python3.6/site-packages/fastai/data_block.py:442: UserWarning: Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.
  warn("Your training set is empty. If this is by design, pass `ignore_empty=True` to remove this warning.")
/opt/conda/lib/python3.6/site-packages/fastai/data_block.py:445: UserWarning: Your validation set is empty. If this is by design, use `split_none()`
                 or pass `ignore_empty=True` when labelling to remove this warning.
  or pass `ignore_empty=True` when labelling to remove this warning.""")
Traceback (most recent call last):
  File "app.py", line 115, in <module>
    image_colorizer = get_image_colorizer(artistic=True)
  File "/data/deoldify/visualize.py", line 390, in get_image_colorizer
    return get_artistic_image_colorizer(render_factor=render_factor)
  File "/data/deoldify/visualize.py", line 413, in get_artistic_image_colorizer
    learn = gen_inference_deep(root_folder=root_folder, weights_name=weights_name)
  File "/data/deoldify/generators.py", line 88, in gen_inference_deep
    learn.load(weights_name)
  File "/opt/conda/lib/python3.6/site-packages/fastai/basic_train.py", line 261, in load
    if purge: self.purge(clear_opt=ifnone(with_opt, False))
  File "/opt/conda/lib/python3.6/site-packages/fastai/basic_train.py", line 313, in purge
    torch.save(state, open(tmp_file, 'wb'))
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/opt/conda/lib/python3.6/site-packages/torch/serialization.py", line 303, in _save
    serialized_storages[key]._write_file(f, _should_read_directly(f))
RuntimeError: write(): fd 6 failed with No space left on device
```

**Comment by jantic** [comment]
Yes, if you want to run this against a GPU you'll need an Nvidia GPU.  It'll still run on CPU otherwise. So it looks like you'll either want to uninstall anything nvidia that was installed. Or just change this  in the quick_start:

`	if nvidia-smi; then
		IPC_HOST="--ipc=host"
		echo "nvidia card found running on GPU"
	else
		IPC_HOST=""
		echo "No nvidia card found running on CPU"
	fi`

To this:

`		IPC_HOST=""
		echo "No nvidia card found running on CPU"
`

**Comment by sklv** [comment]
I made the changes to `quick_start.sh` but it made no difference to the error. In fact, I don't think the behaviour changed at all, as I never installed any nvidia libs or tools on the system - I'm pretty sure `IPC_HOST=""` was the code path on the original attempt as the `nvidia-smi` was never present on my system.

I think the root cause of `No space left on device` is unrelated.

However it's good to know that it should run on the CPU.

I'd be happy to provide any troubleshooting info.

**Comment by jqueguiner** [comment]
No space left on device is because you don’t have enough space to pull docker image 

docker system is similar to git.

it’s pulling image layers (layer are a bit lit commits) 

so if you don’t have enough space on your laptop/desktop it will not be able to download all docker layer and therefore not able to run it.

yiu have also to keep in mind that docker as a limited space on disk that you can adjust and might be also the source of the issue


I suggested looking into this resolution 
https://stackoverflow.com/questions/30604846/docker-error-no-space-left-on-device
