### ISSUE TITLE
Issues running docker container & issues getting a response from the API

### ISSUE THREAD

**Issue by CodeClouds-Guru** [jantic/DeOldify#301]
Good day, after some troubleshooting and reinstalling everything I've managed to get the software running and I can make calls to the api however there seems to be some discrepancies and errors that aren't making much sense. 

Discrepency #1 is that the provided API call example is using source_url parameter while the API only knows of a url parameter, trying to run the example CURL request call fails. 

```
185.202.0.18 - - [31/Dec/2020 10:01:25] code 400, message Bad HTTP/0.9 request type ('\x03\x00\x00+&�\x0
185.202.0.18 - - [31/Dec/2020 10:01:25] "+&�
  File "app.py", line 61, in process_image
    url = request.json["url"]
```

Changing the parameter to URL instead of source_url results in the following error message.

```
Traceback (most recent call last):
  File "app.py", line 77, in process_image
    callback = send_file(output_path, mimetype='image/jpeg')
  File "/home/testing/.local/lib/python3.6/site-packages/flask/helpers.py", line 629, in send_file
    file = open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/home/testing/DeOldify/data/result_images/a4ccf03a-c25b-4e17-aae6-88300a42a7a3.jpeg'
```
So it appears that the image is not being saved to the result_images folder after processing? 

Also attempting to run using ./quick_start.sh image_api fails with this message.

`
/usr/local/bin/run_image_api: line 2:    29 Illegal instruction     (core dumped) python3 app.py
`

I also tried running the app using docker with the provided documented method but that also fails without any insights.

Starting docker looks like it runs at first

```
http://2602:ff50:0:56:225:90ff:fedc:37a6:5000
97bf18410d6f0b1097336acc44327d13a0bbe17a326542d810733765766f9bef
```

Running docker ps shows no running docker images
Running docker ps -a shows the docker image started and almost immediately exited

```
97bf18410d6f   deoldify_api   "python3 app.py"         24 seconds ago   Exited (132) 22 seconds ago             nice_chebyshev
```

The server has the following specs and is running a fresh install of Ubuntu 18.04 LTS, all drivers are up to date including nvidia drivers and nvidia-docker , followed the readme exactly.

GPU - NVIDIA GeForce GTX 1070Ti GPU
CPU - Intel Xeon E5-2650 v2 2.60GHz 8C/16T
RAM - 32GB ECC RAM
HDD - 250 GB SSD Storage

Python3 version is 3.6.9
Python2 version is 2.7.17

**Comment by CodeClouds-Guru** [comment]
I can see images are being created in the result_images folder however the application is still returning the error message and no response from the api call. I can only get the API to run at all by manually typing ```python3 app.py``` but this does not appear to be the correct way to run the program according to the documentation. No method of running the program seems to work properly.

**Comment by CodeClouds-Guru** [comment]
It looks like FileNotFoundError: [Errno 2] No such file or directory: '/home/testing/DeOldify/data/result_images/a4ccf03a-c25b-4e17-aae6-88300a42a7a3.jpeg'

Is because its looking for the images under /data/result_images however its creating the folders in the main directory so the real path should be '/home/testing/DeOldify/data/result_images/a4ccf03a-c25b-4e17-aae6-88300a42a7a3.jpeg'

**Comment by CodeClouds-Guru** [comment]
@jantic are you able to provide any insights on this? Thank you

**Comment by jantic** [comment]
So I'll have to add this disclaimer: I personally don't use the docker image so I tend to defer to the creator @jqueguiner  on design questions, because they're the one who will be affected most.

That being said- I personally don't see why you'd want to save the images in the first place with an api like this. There is an alternative method:  get_transformed_image that doesn't plot the image nor save it as side effects- it just returns the processed image.  That seems to me to be the real solution here.

@jqueguiner , what do you think?

**Comment by CodeClouds-Guru** [comment]
> That being said- I personally don't see why you'd want to save the images in the first place with an api like this. There is an alternative method: get_transformed_image that doesn't plot the image nor save it as side effects- it just returns the processed image. That seems to me to be the real solution here.

This is the default behavior when running the application using ```python3 app.py``` without doing any extra modifications, is there a starting parameter that needs set when doing this? None of the recommended ways of running the API are working, only by manually running ```python3 app.py``` can I get the API to partly work

**Comment by jantic** [comment]
@CodeClouds-Guru What I'm saying is this is really @jqueguiner 's baby and I don't want to change anything without his input first, as it's a pretty big behavior change. What I'd suggest to you though is 

- debug assuming there's something missed in the deployment on your end.  This is a pretty safe assumption because there haven't been reports of this behavior previous and things haven't changed much with the api. 
- if you're up to it/can do it that you modify the code according to what I suggested.

**Comment by jqueguiner** [comment]
@CodeClouds-Guru can you try following the new QuickStart doc in read me and let me know if the problem persist. Sorry for the doc glitch.

also results are not being saved permanently on the API docker it’s a temporary file being saved then served through the API and then removed form the API server in order to avoid disk usage and preserve data privacy.

**Comment by jantic** [comment]
Closing due to inactivity.
