### ISSUE TITLE
How to use only pytorch to build DeOldify?

### ISSUE THREAD

**Issue by lkp520** [jantic/DeOldify#375]
I try to use pytorch to build the model deoldify, but when I complete all classes and functions, I meet the problem: 
```python
Error:
Traceback (most recent call last):
  File "/data/likengpeng/DeOldify_torch/deoldify/dataset.py", line 860, in _check_kwargs
    try: x.apply_tfms(tfms, **kwargs)
AttributeError: 'PosixPath' object has no attribute 'apply_tfms'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ColorizeTrainingStable.py", line 109, in <module>
    data_gen = get_data(bs=bs, sz=sz, keep_pct=keep_pct)
  File "ColorizeTrainingStable.py", line 49, in get_data
    return get_colorize_data(sz=sz, bs=bs, crappy_path=path_lr, good_path=path_hr, 
  File "/data/likengpeng/DeOldify_torch/deoldify/dataset.py", line 1756, in get_colorize_data
    src.label_from_func(lambda x: good_path / x.relative_to(crappy_path))
  File "/data/likengpeng/DeOldify_torch/deoldify/dataset.py", line 756, in transform
    self.train.transform(tfms[0], **kwargs)  # may be problem. How to solve it??
  File "/data/likengpeng/DeOldify_torch/deoldify/dataset.py", line 996, in transform
    _check_kwargs(self.x, tfms, **kwargs)
  File "/data/likengpeng/DeOldify_torch/deoldify/dataset.py", line 862, in _check_kwargs
    raise Exception(f"It's not possible to apply those transforms to your dataset:\n {e}")
Exception: It's not possible to apply those transforms to your dataset:
 'PosixPath' object has no attribute 'apply_tfms'
```

**Comment by jantic** [comment]
I'm not sure what you're trying to do here exactly or what's motivating it but that function it's complaining about (apply_tfms) is in the fastai library. We're not going to be making DeOldify installable without installing fastai and its dependencies if that's what you're attempting- we have no motivation to make our lives more difficult like that!
