### ISSUE TITLE
Found another issue/bug...

### ISSUE THREAD

**Issue by jdc4429** [jantic/DeOldify#471]
Hey Jason,

I'm not sure why this is happening.  But when colorizing from file (not URL), after it's done creating the color frames but before it has created the no_audio version it crashes and states the file doesn't exist! It does this after waiting 2-3 hours for the encoding to finsh.  I made my own script to piece everything together after it fails so I can work around it but I don't see any reason why it's happening to begin with.  It seems to just delete the file! Here is a copy of the error output...

Traceback (most recent call last):█| 100.00% [85223/85223 2:42:11<00:00]]
  File "/home/jeff/DeOldify/FileColorizer.py", line 48, in <module>
    result_path = colorizer.colorize_from_file_name(file_name_ext, render_factor=render_factor)    
  File "/home/jeff/DeOldify/deoldify/visualize.py", line 392, in colorize_from_file_name
    return self._colorize_from_path(
  File "/home/jeff/DeOldify/deoldify/visualize.py", line 407, in _colorize_from_path
    return self._build_video(source_path)
  File "/home/jeff/DeOldify/deoldify/visualize.py", line 339, in _build_video
    shutil.copyfile(str(colorized_path), str(result_path))
  File "/home/jeff/anaconda3/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'video/result/77 Sunset Strip - S01E07 - All Our Yesterdays.mkv'

**Comment by jdc4429** [comment]
I think this is from another path I have to set.. ie result_path=None.Source_url=None
